import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

const CopyButton: React.FC = () => {
  const [copied, setCopied] = useState(false);
  useEffect(() => {
    if (copied) {
      setTimeout(() => {
        setCopied(false);
      }, 2000);
    }
  }, [copied]);
  return (
    <button
      className="border-2 py-2 px-4 mt-2 rounded hover:bg-gray-200 transition"
      onClick={() => {
        window.navigator.clipboard.writeText("npx create-next-app --ts");
        setCopied(true);
      }}
    >
      {copied ? "Copied Successfully" : "Copy"}
    </button>
  );
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center animate-fade-in">
        <div className="text-xl p-4">We Recommend</div>
        <code className="bg-gray-700 transition hover:bg-gray-500 text-gray-200 px-4 py-2 rounded">
          npx create-next-app --ts
        </code>
        <CopyButton />
      </div>
    </div>
  );
}
